"""
Scopus CSV Format Learner & Converter
=====================================
1. User uploads CORRECT format file (Category B) — app learns the structure
2. User uploads INCORRECT format file(s) (Category A/C) — app converts to match learned structure
"""

import streamlit as st
import pandas as pd
import csv
import io
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Literal


# ─────────────────────────────────────────────────────────────────────────────
# PHASE 1: LEARN FROM CORRECT FORMAT
# ─────────────────────────────────────────────────────────────────────────────

def learn_from_correct_format(content: str) -> Dict:
    """Parse correct format and extract structural information."""
    df = pd.read_csv(io.StringIO(content), dtype=str, keep_default_na=False)
    
    structure = {
        'columns': list(df.columns),
        'num_columns': len(df.columns),
        'sample_row': df.iloc[0].to_dict() if len(df) > 0 else {},
    }
    
    return structure


# ─────────────────────────────────────────────────────────────────────────────
# PHASE 2: DETECT AND FIX INCORRECT FORMAT
# ─────────────────────────────────────────────────────────────────────────────

def detect_format_type(content: str) -> Literal['correct', 'incorrect', 'unknown']:
    """Detect if file is correct or incorrect Scopus CSV format."""
    first_line = content.split('\n')[0] if content else ''
    
    # Incorrect format indicators (strong)
    if first_line.endswith(';' * 50):  # Trailing semicolons
        return 'incorrect'
    if first_line.count('""') > 20:  # Doubled quotes
        return 'incorrect'
    
    # Correct format indicators
    if first_line.count('","') >= 20 and not first_line.endswith(';'):
        return 'correct'
    
    return 'unknown'


def fix_incorrect_scopus_csv(content: str) -> str:
    """
    Fixes the specific 'incorrect' Scopus CSV format by transforming it 
    back into a standard correct CSV format.
    
    The incorrect format is generated by wrapping the entire row in an extra 
    layer of quotes, doubling all internal quotes, and adding trailing semicolons.
    The first column is originally unquoted.
    """
    lines = content.splitlines()
    fixed_lines = []
    
    for line in lines:
        line = line.strip()
        if not line:
            fixed_lines.append("")
            continue
        
        # 1. Remove trailing semicolons
        line = line.rstrip(';')
        
        # 2. Remove the outer wrapper quotes
        if line.startswith('"') and line.endswith('"'):
            line = line[1:-1]
            
        # 3. Unescape the doubled quotes
        line = line.replace('""', '"')
        
        # 4. Quote the first field (which was originally unquoted)
        # The first field is Authors or author names, which do not contain commas.
        # So we can safely find the first comma and wrap the first field in quotes.
        if ',' in line and not line.startswith('"'):
            line = '"' + line.replace(',', '","', 1)
            
        fixed_lines.append(line)
        
    return '\n'.join(fixed_lines)


# ─────────────────────────────────────────────────────────────────────────────
# OUTPUT FORMATTING
# ─────────────────────────────────────────────────────────────────────────────

def format_as_correct_csv(df: pd.DataFrame) -> str:
    """Format DataFrame as correct Scopus CSV."""
    output = io.StringIO()
    df.to_csv(output, index=False, quoting=csv.QUOTE_ALL, encoding='utf-8')
    return output.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
# STREAMLIT UI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    st.set_page_config(page_title="Scopus CSV Format Learner", page_icon="🎓", layout="wide")
    
    st.title("🎓 Scopus CSV Format Learner & Converter")
    st.markdown("""
    **Two-phase workflow:**
    1. **Learn**: Upload a correctly-formatted Scopus CSV (Category B)
    2. **Convert**: Upload incorrectly-formatted files (Category A/C) to convert them
    """)
    
    # Initialize session state
    if 'learned_structure' not in st.session_state:
        st.session_state.learned_structure = None
    
    # ── Phase 1: Learn ──────────────────────────────────────────────────────
    st.header("Phase 1: Learn Correct Format")
    
    correct_file = st.file_uploader(
        "Upload a CORRECTLY formatted Scopus CSV (Category B)",
        type=['csv'],
        key='correct_uploader'
    )
    
    if correct_file:
        content = correct_file.read().decode('utf-8-sig')
        fmt = detect_format_type(content)
        
        if fmt == 'incorrect':
            st.error("❌ This file appears to be in INCORRECT format. Please upload a correct one.")
        else:
            try:
                structure = learn_from_correct_format(content)
                st.session_state.learned_structure = structure
                
                st.success(f"✅ Learned structure: **{structure['num_columns']} columns**")
                
                with st.expander("View learned structure"):
                    st.json({
                        'columns': structure['columns'],
                        'num_columns': structure['num_columns']
                    })
            except Exception as e:
                st.error(f"❌ Failed to learn: {e}")
    
    # ── Phase 2: Convert ────────────────────────────────────────────────────
    st.header("Phase 2: Convert Incorrect Format")
    
    if st.session_state.learned_structure is None:
        st.info("⬆️ Please upload a correct format file first to enable conversion.")
        return
    
    incorrect_files = st.file_uploader(
        "Upload INCORRECTLY formatted Scopus CSV files (Category A/C)",
        type=['csv'],
        accept_multiple_files=True,
        key='incorrect_uploader'
    )
    
    if not incorrect_files:
        st.info("⬆️ Upload incorrect format files to convert")
        return
    
    for uploaded_file in incorrect_files:
        st.divider()
        st.subheader(f"📄 {uploaded_file.name}")
        
        content = uploaded_file.read().decode('utf-8-sig')
        fmt = detect_format_type(content)
        
        if fmt == 'correct':
            st.warning("⚠️ This file appears to already be in correct format. Skipping conversion.")
            continue
        
        if fmt == 'unknown':
            st.warning("⚠️ Could not detect format. Attempting conversion anyway.")
        
        st.info("🔍 Detected: **Incorrect format** — converting...")
        
        try:
            with st.spinner("Converting..."):
                # FIX THE FORMAT FIRST
                fixed_content = fix_incorrect_scopus_csv(content)
                
                # NOW PARSE AS NORMAL CSV
                df = pd.read_csv(io.StringIO(fixed_content), dtype=str, keep_default_na=False)
                
                # Verify columns match learned structure
                expected_cols = st.session_state.learned_structure['columns']
                missing_cols = [c for c in expected_cols if c not in df.columns]
                extra_cols = [c for c in df.columns if c not in expected_cols]
                
                if missing_cols:
                    st.warning(f"⚠️ Missing columns compared to learned structure: {missing_cols}")
                if extra_cols:
                    st.warning(f"⚠️ Extra columns not in learned structure: {extra_cols}")
                    
                # Reorder columns to match learned structure
                df = df[[c for c in expected_cols if c in df.columns]]
                
                # Add any missing columns as empty
                for col in missing_cols:
                    df[col] = ''
                    
                # Final reorder to exactly match learned structure
                df = df[expected_cols]
            
            st.success(f"✅ Converted: **{len(df)} rows** × **{len(df.columns)} columns**")
            
            with st.expander("Preview"):
                st.dataframe(df.head(3), use_container_width=True)
            
            # Download buttons
            col1, col2 = st.columns(2)
            
            base_name = Path(uploaded_file.name).stem
            
            with col1:
                csv_output = format_as_correct_csv(df)
                st.download_button(
                    label=f"⬇️ Download `{base_name}_formatted.csv`",
                    data=csv_output,
                    file_name=f"{base_name}_formatted.csv",
                    mime="text/csv",
                    use_container_width=True
                )
            
            with col2:
                json_output = df.to_json(orient='records', indent=2, force_ascii=False)
                st.download_button(
                    label=f"⬇️ Download `{base_name}_structured.json`",
                    data=json_output,
                    file_name=f"{base_name}_structured.json",
                    mime="application/json",
                    use_container_width=True
                )
                
        except Exception as e:
            st.error(f"❌ Conversion failed: {e}")
            st.exception(e)


if __name__ == "__main__":
    main()
